dourbit holy on urbit confirm install as a fail-safe before running most commands

diff --git a/bin-fn/dourbit b/bin-fn/dourbit
--- a/bin-fn/dourbit
+++ b/bin-fn/dourbit
@@ -70,6 +70,12 @@ dourbit() {
         exit 1
       fi
 
+    # silently confirm urbit is installed, as the rest of commands will need it
+    elif ! silent holy on urbit; then
+      errcho "Not Installed."
+      dourbit confirm
+      exit 1
+
     elif [ $cmd == "version" ]; then
       dourbit urbit -R
       specho $(docker --version)
