check-fn gracious fail if not found

diff --git a/bin/check-fn b/bin/check-fn
--- a/bin/check-fn
+++ b/bin/check-fn
@@ -16,5 +16,5 @@ if [ $# -eq 0 ]; then
   echo "$count exported functions above"
   echo "($(basename $0) name # for code)"
 else
-  declare -fp "$1"
+  declare -fp "$1" 2> /dev/null || echo "$1 NOT FOUND"
 fi
