a new format for scripts that can be either run or sourced to use as functions

diff --git a/bin/install-xr b/bin/install-xr
--- a/bin/install-xr
+++ b/bin/install-xr
@@ -1,23 +1,28 @@
 #!/usr/bin/env bash
 
-if [[ $# -lt 1 ]]; then
-    echo "Usage: $(basename $0) filepath/of/installer-to-run-and-remove"
-    exit 1
-fi
+COMMAND_FN=install-xr
+install-xr() {
+  if [[ $# -lt 1 ]]; then
+      echo "Usage: $(basename $0) filepath/of/installer-to-run-and-remove"
+      exit 1
+  fi
 
-installer=$1
+  local installer=$1
 
-if [ ! -f $installer ]; then
-    echo "$installer"
-    echo "File not found!"
-    exit 1
-fi
+  if [ ! -f $installer ]; then
+      echo "$installer"
+      echo "File not found!"
+      exit 1
+  fi
 
-# make it an executable file
-chmod +x $installer
+  # make it an executable file
+  chmod +x $installer
 
-# run it to install whatever
-$installer
+  # run it to install whatever
+  $installer
 
-# remove it for a clean exit
-rm $installer
+  # remove it for a clean exit
+  rm $installer
+}
+
+[ $(basename $0) = $COMMAND_FN ] && $COMMAND_FN "$@"
