holy confirm platform/node + nvm-on + plans for nvm-dir

diff --git a/on/confirm/urbit b/on/confirm/urbit
--- a/on/confirm/urbit
+++ b/on/confirm/urbit
@@ -12,7 +12,7 @@ confirm() {
     silent ls $dir
     if [ $? -ne 0 ]; then
       good=false
-      echo "Not Found: $dir"
+      >&2 echo "Not Found: $dir"
     fi
   done
   $good; return
