holy and dourbit -- functions return rather than exit

diff --git a/cmd/dourbit b/cmd/dourbit
--- a/cmd/dourbit
+++ b/cmd/dourbit
@@ -71,14 +71,14 @@ dourbit() {
         echo "All is in order."
       else
         echo "Maybe run this for an easy fix: $COMMAND_FN install"
-        exit 1
+        false; return
       fi
 
     # silently confirm urbit is installed, the rest of commands will need it
     elif ! holy on urbit >/dev/null 2>&1; then
         >&2 echo "Not Installed."
         dourbit confirm
-        exit 1
+        false; return
 
     elif [ $cmd == "version" ]; then
       dourbit urbit -R
@@ -132,11 +132,11 @@ dourbit() {
       if [[ ! -z $(docker images -q $wut) ]]; then
         echo $wut
       else
-        echo "Not found: $wut"
+        >&2 echo "Not found: $wut"
         if [[ ! -z $(dourbit tagged $wut) ]]; then
           echo "Can build with: dourbit build $wut"
         fi
-        exit 1
+        false; return
       fi
 
     elif [ $cmd == "images" ]; then
@@ -147,13 +147,13 @@ dourbit() {
     elif [ $cmd == "build" ]; then
       local tag=$(URBIT_EAGER=true dourbit foremost $@)
       if [ "$tag" == "" ]; then
-        echo "Not Found: ${1-'urbit-'}*"
-        exit 1
+        >&2 echo "Not Found: ${1-'urbit-'}*"
+        false; return
       elif [ $(dourbit existing $tag) ]; then
         echo "Pointless, will not build."
         echo "Have This: $tag"
         echo "Docker ID: $(dourbit image-id $tag)"
-        exit 0
+        true; return
       else
         cd $(repos)/urbit-docker && \
           git pull && \
diff --git a/cmd/holy b/cmd/holy
--- a/cmd/holy
+++ b/cmd/holy
@@ -159,7 +159,7 @@ holy() {
       # probably $the you path from above as the one should always be found
       if ! [ -d $where ]; then
         echo "Attempted: holy $the init"
-        echo "Not Found: $where"
+        >&2 echo "Not Found: $where"
         false; return
       fi
       # now what do we run?
@@ -185,7 +185,7 @@ holy() {
           false; return
         fi
       else
-        echo "Not found: $shell"
+        >&2 echo "Not found: $shell"
         echo -n "Can try it with: "
         # only the executables minus some files excluded via the grep below
         # that has remained to be just once for the time being
@@ -238,7 +238,7 @@ holy() {
       installable $1
       local status=$?
       [[ $# -ne 0 && $status -eq 0 ]] && echo $1
-      exit $status
+      return $status
 
     elif [ $cmd == "confirm" ]; then
       local able=$1
