holy install can take additional args and pass them onto the given script

diff --git a/cmd/holy b/cmd/holy
--- a/cmd/holy
+++ b/cmd/holy
@@ -220,14 +220,15 @@ holy() {
       elif installable $able; then
         tis-true $HOLY_EAGER && \
           holy update >/dev/null 2>&1
-        $path
+        shift # ability saved as $able (the relative $path to install script)
+        $path $@ # install $path, giving it the rest of $@ args
         if [ $? -eq 0 ]; then
           cd "$HOLY_HOME"
           mkdir -p $(echo "$onit" | rev | cut -d'/' -f2- | rev)
           echo $(git show --format="%h" --no-patch) > $onit
           if [ $? -ne 0 ]; then >&2 echo "Targeting: '$onit'"; fi
         else
-          >&2 echo "Failed: $COMMAND_FN $cmd $@"
+          >&2 echo "Failed: $COMMAND_FN $cmd $able $@"
           false; return
         fi
       else
