new holy in error of not installable

diff --git a/cmd/holy b/cmd/holy
--- a/cmd/holy
+++ b/cmd/holy
@@ -231,7 +231,13 @@ holy() {
           false; return
         fi
       else
-        >&2 echo "Not found: $path"
+        if [ -f $path ]; then
+          # path to file exists, this must be an executable permissions issue
+          >&2 echo "Not installable: $path"
+          >&2 echo "chmod +x please"
+        else
+          >&2 echo "Not found: $path"
+        fi
         false; return
       fi
 
